import './globals.css';
import { Nunito } from 'next/font/google';
import Navbar from  './components/navbar/Navbar';
import ClientOnly from './components/ClientOnly';

// META DATA
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// FONT
const font = Nunito({ subsets: ['latin'] })

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <ClientOnly>
          <Navbar/>
        </ClientOnly>
        {children}
      </body>
    </html>
  )
}
